# Generated by Django 4.2 on 2025-08-31 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto. Ej: iPhone 15 Pro Max', max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras (EAN-13). Se genera automáticamente.', max_length=13, unique=True)),
                ('imagen_codigo_barras', models.ImageField(blank=True, upload_to='codigos_de_barras/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proveedor', max_length=150, unique=True)),
                ('contacto', models.CharField(blank=True, help_text='Persona de contacto', max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_variante', models.CharField(help_text='Descripción de la variante. Ej: 128GB / Azul Titanio', max_length=150)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'unique_together': {('producto', 'nombre_variante')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.proveedor'),
        ),
        migrations.CreateModel(
            name='DetalleIphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(help_text='IMEI único del equipo', max_length=15, unique=True)),
                ('salud_bateria', models.PositiveIntegerField(help_text='Porcentaje de salud de la batería (ej: 98)')),
                ('fallas_detectadas', models.TextField(blank=True, help_text='Descripción de cualquier falla o detalle', null=True)),
                ('fecha_compra', models.DateField()),
                ('variante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_iphone', to='inventario.productovariante')),
            ],
            options={
                'verbose_name': 'Detalle de iPhone',
                'verbose_name_plural': 'Detalles de iPhones',
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_precio', models.CharField(choices=[('Minorista', 'Minorista'), ('Mayorista', 'Mayorista')], default='Minorista', max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo de adquisición del producto', max_digits=10)),
                ('precio_venta_normal', models.DecimalField(decimal_places=2, help_text='Precio de venta estándar', max_digits=10)),
                ('precio_venta_minimo', models.DecimalField(decimal_places=2, help_text='Precio mínimo al que se puede vender', max_digits=10)),
                ('precio_venta_descuento', models.DecimalField(blank=True, decimal_places=2, help_text='Precio con descuento (opcional)', max_digits=10, null=True)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='inventario.productovariante')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'unique_together': {('variante', 'tipo_precio')},
            },
        ),
    ]
