# Generated by Django 4.2 on 2025-08-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el producto está activo y visible para la venta'),
        ),
    ]
