# Generated by Django 4.2 on 2025-09-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares Estadounidenses (USD)')], default='ARS', max_length=3),
        ),
    ]
