# Generated by Django 4.2 on 2025-09-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_precio_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleiphone',
            name='fecha_compra',
        ),
        migrations.AddField(
            model_name='detalleiphone',
            name='es_plan_canje',
            field=models.BooleanField(default=False, help_text='Marcar si este equipo fue recibido como parte de un Plan Canje'),
        ),
        migrations.AlterField(
            model_name='detalleiphone',
            name='imei',
            field=models.CharField(blank=True, help_text='IMEI único del equipo', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='detalleiphone',
            name='salud_bateria',
            field=models.PositiveIntegerField(blank=True, help_text='Porcentaje de salud de la batería (ej: 98)', null=True),
        ),
        migrations.AlterField(
            model_name='precio',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares Estadounidenses (USD)')], default='USD', max_length=3),
        ),
    ]
