# Generated by Django 5.2.8 on 2025-11-07 01:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_detalleiphone_fecha_compra_and_more'),
    ]

    operations = [
        # ------------------------------------------------------------------
        # 1) DetalleIphone: solo estado (no tocar DB para evitar errores)
        # ------------------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='detalleiphone',
                    name='variante',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='DetalleIphone',
                ),
            ],
            database_operations=[],
        ),

        # ------------------------------------------------------------------
        # 2) Opciones de modelos
        # ------------------------------------------------------------------
        migrations.AlterModelOptions(
            name='categoria',
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AlterModelOptions(
            name='precio',
            options={
                'ordering': ['variante__sku', 'tipo', 'moneda'],
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-actualizado', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='productovariante',
            options={
                'ordering': ['producto__nombre', 'sku'],
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
            },
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre']},
        ),

        # ------------------------------------------------------------------
        # 3) unique_together -> vacío (solo estado)
        # ------------------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(name='precio', unique_together=set()),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(name='productovariante', unique_together=set()),
            ],
            database_operations=[],
        ),

        # ------------------------------------------------------------------
        # 4) Eliminaciones problemáticas: SOLO ESTADO
        #    (evita "Can't DROP ...")
        # ------------------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField(model_name='producto', name='fecha_creacion')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField(model_name='producto', name='imagen')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField(model_name='proveedor', name='contacto')],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField(model_name='proveedor', name='fecha_creacion')],
            database_operations=[],
        ),

        # ------------------------------------------------------------------
        # 5) Nuevos campos - robustos (ADD COLUMN IF NOT EXISTS)
        #    Se actualiza el ESTADO de Django y se aplica SQL defensivo.
        # ------------------------------------------------------------------

        # categoria.descripcion
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='categoria',
                    name='descripcion',
                    field=models.TextField(blank=True, default=""),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_categoria
                    ADD COLUMN IF NOT EXISTS descripcion LONGTEXT NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_categoria
                    DROP COLUMN IF EXISTS descripcion;
                    """,
                )
            ],
        ),

        # precio.activo
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='precio',
                    name='activo',
                    field=models.BooleanField(default=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_precio
                    ADD COLUMN IF NOT EXISTS activo TINYINT(1) NOT NULL DEFAULT 1;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_precio
                    DROP COLUMN IF EXISTS activo;
                    """,
                )
            ],
        ),

        # precio.actualizado
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='precio',
                    name='actualizado',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_precio
                    ADD COLUMN IF NOT EXISTS actualizado DATETIME NOT NULL
                    DEFAULT CURRENT_TIMESTAMP
                    ON UPDATE CURRENT_TIMESTAMP;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_precio
                    DROP COLUMN IF EXISTS actualizado;
                    """,
                )
            ],
        ),

        # precio.creado
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='precio',
                    name='creado',
                    field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_precio
                    ADD COLUMN IF NOT EXISTS creado DATETIME NOT NULL
                    DEFAULT CURRENT_TIMESTAMP;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_precio
                    DROP COLUMN IF EXISTS creado;
                    """,
                )
            ],
        ),

        # precio.precio
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='precio',
                    name='precio',
                    field=models.DecimalField(decimal_places=2, max_digits=12, default=0),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_precio
                    ADD COLUMN IF NOT EXISTS precio DECIMAL(12,2) NOT NULL DEFAULT 0;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_precio
                    DROP COLUMN IF EXISTS precio;
                    """,
                )
            ],
        ),

        # precio.tipo
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='precio',
                    name='tipo',
                    field=models.CharField(
                        choices=[('MINORISTA', 'Minorista'), ('MAYORISTA', 'Mayorista')],
                        default='MINORISTA',
                        max_length=20,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_precio
                    ADD COLUMN IF NOT EXISTS tipo VARCHAR(20) NOT NULL DEFAULT 'MINORISTA';
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_precio
                    DROP COLUMN IF EXISTS tipo;
                    """,
                )
            ],
        ),

        # producto.creado
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='producto',
                    name='creado',
                    field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_producto
                    ADD COLUMN IF NOT EXISTS creado DATETIME NOT NULL
                    DEFAULT CURRENT_TIMESTAMP;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_producto
                    DROP COLUMN IF EXISTS creado;
                    """,
                )
            ],
        ),

        # producto.actualizado (nuevo campo, ya que el viejo era "ultima_actualizacion")
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='producto',
                    name='actualizado',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_producto
                    ADD COLUMN IF NOT EXISTS actualizado DATETIME NOT NULL
                    DEFAULT CURRENT_TIMESTAMP
                    ON UPDATE CURRENT_TIMESTAMP;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_producto
                    DROP COLUMN IF EXISTS actualizado;
                    """,
                )
            ],
        ),

        # productovariante.activo
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='productovariante',
                    name='activo',
                    field=models.BooleanField(default=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_productovariante
                    ADD COLUMN IF NOT EXISTS activo TINYINT(1) NOT NULL DEFAULT 1;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_productovariante
                    DROP COLUMN IF EXISTS activo;
                    """,
                )
            ],
        ),

        # productovariante.actualizado
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='productovariante',
                    name='actualizado',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_productovariante
                    ADD COLUMN IF NOT EXISTS actualizado DATETIME NOT NULL
                    DEFAULT CURRENT_TIMESTAMP
                    ON UPDATE CURRENT_TIMESTAMP;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_productovariante
                    DROP COLUMN IF EXISTS actualizado;
                    """,
                )
            ],
        ),

        # productovariante.atributo_1
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='productovariante',
                    name='atributo_1',
                    field=models.CharField(blank=True, max_length=120),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_productovariante
                    ADD COLUMN IF NOT EXISTS atributo_1 VARCHAR(120) NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_productovariante
                    DROP COLUMN IF EXISTS atributo_1;
                    """,
                )
            ],
        ),

        # productovariante.atributo_2
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='productovariante',
                    name='atributo_2',
                    field=models.CharField(blank=True, max_length=120),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_productovariante
                    ADD COLUMN IF NOT EXISTS atributo_2 VARCHAR(120) NULL;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_productovariante
                    DROP COLUMN IF EXISTS atributo_2;
                    """,
                )
            ],
        ),

        # productovariante.creado
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='productovariante',
                    name='creado',
                    field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_productovariante
                    ADD COLUMN IF NOT EXISTS creado DATETIME NOT NULL
                    DEFAULT CURRENT_TIMESTAMP;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_productovariante
                    DROP COLUMN IF EXISTS creado;
                    """,
                )
            ],
        ),

        # productovariante.sku  (antes tiró duplicado => estado + SQL IF NOT EXISTS)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='productovariante',
                    name='sku',
                    field=models.CharField(max_length=64, unique=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_productovariante
                    ADD COLUMN IF NOT EXISTS sku VARCHAR(64) UNIQUE;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_productovariante
                    DROP COLUMN IF EXISTS sku;
                    """,
                )
            ],
        ),

        # productovariante.stock_actual
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='productovariante',
                    name='stock_actual',
                    field=models.IntegerField(default=0),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_productovariante
                    ADD COLUMN IF NOT EXISTS stock_actual INT NOT NULL DEFAULT 0;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_productovariante
                    DROP COLUMN IF EXISTS stock_actual;
                    """,
                )
            ],
        ),

        # productovariante.stock_minimo
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='productovariante',
                    name='stock_minimo',
                    field=models.IntegerField(default=0),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_productovariante
                    ADD COLUMN IF NOT EXISTS stock_minimo INT NOT NULL DEFAULT 0;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_productovariante
                    DROP COLUMN IF EXISTS stock_minimo;
                    """,
                )
            ],
        ),

        # proveedor.activo
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='proveedor',
                    name='activo',
                    field=models.BooleanField(default=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_proveedor
                    ADD COLUMN IF NOT EXISTS activo TINYINT(1) NOT NULL DEFAULT 1;
                    """,
                    reverse_sql="""
                    ALTER TABLE inventario_proveedor
                    DROP COLUMN IF EXISTS activo;
                    """,
                )
            ],
        ),

        # ------------------------------------------------------------------
        # 6) AlterField (tipo/unique/relaciones). Se dejan normales.
        # ------------------------------------------------------------------
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='precio',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='productos',
                to='inventario.categoria',
            ),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_codigo_barras',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='productos',
                to='inventario.proveedor',
            ),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),

        # ------------------------------------------------------------------
        # 7) Índices
        #    Para evitar choques por índices existentes, los críticos de SKU
        #    se dejan SOLO-ESTADO.
        # ------------------------------------------------------------------
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre'], name='idx_categoria_nombre'),
        ),
        migrations.AddIndex(
            model_name='precio',
            index=models.Index(fields=['activo'], name='idx_precio_activo'),
        ),
        migrations.AddIndex(
            model_name='precio',
            index=models.Index(fields=['variante', 'tipo', 'moneda'], name='idx_precio_var_tipo_mon'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='idx_producto_activo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='idx_producto_nombre'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barras'], name='idx_producto_cod_barras'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='productovariante',
                    index=models.Index(fields=['sku'], name='idx_var_sku'),
                ),
            ],
            database_operations=[],  # evita error si ya existe un índice similar
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['activo'], name='idx_var_activo'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['stock_actual'], name='idx_var_stock'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['activo'], name='idx_proveedor_activo'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nombre'], name='idx_proveedor_nombre'),
        ),

        # ------------------------------------------------------------------
        # 8) Eliminaciones finales (DROP COLUMN IF EXISTS) + solo-estado
        # ------------------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='precio', name='costo'),
                migrations.RemoveField(model_name='precio', name='precio_venta_descuento'),
                migrations.RemoveField(model_name='precio', name='precio_venta_minimo'),
                migrations.RemoveField(model_name='precio', name='precio_venta_normal'),
                migrations.RemoveField(model_name='precio', name='tipo_precio'),
                migrations.RemoveField(model_name='productovariante', name='nombre_variante'),
                migrations.RemoveField(model_name='productovariante', name='stock'),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_precio
                      DROP COLUMN IF EXISTS costo,
                      DROP COLUMN IF EXISTS precio_venta_descuento,
                      DROP COLUMN IF EXISTS precio_venta_minimo,
                      DROP COLUMN IF EXISTS precio_venta_normal,
                      DROP COLUMN IF EXISTS tipo_precio;
                    """,
                    reverse_sql="""
                    -- No se recrean automáticamente en reversa.
                    """,
                ),
                migrations.RunSQL(
                    """
                    ALTER TABLE inventario_productovariante
                      DROP COLUMN IF EXISTS nombre_variante,
                      DROP COLUMN IF EXISTS stock;
                    """,
                    reverse_sql="""
                    -- No se recrean automáticamente en reversa.
                    """,
                ),
            ],
        ),
    ]
