# Generated by Django 5.2 on 2025-03-07 00:00
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0007_squash_fix_state_only"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS inventario_detalleiphone;",
            reverse_sql="",
        ),
        migrations.CreateModel(
            name="DetalleIphone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("imei", models.CharField(blank=True, help_text="IMEI único del equipo", max_length=15, null=True, unique=True)),
                ("salud_bateria", models.PositiveIntegerField(blank=True, help_text="Porcentaje de salud de la batería (1-100)", null=True)),
                ("fallas_detectadas", models.TextField(blank=True, help_text="Observaciones o detalles a tener en cuenta")),
                ("es_plan_canje", models.BooleanField(default=False, help_text="Indica si fue recibido como parte de un plan canje")),
                ("costo_usd", models.DecimalField(blank=True, decimal_places=2, help_text="Costo de adquisición en USD", max_digits=10, null=True)),
                ("precio_venta_usd", models.DecimalField(decimal_places=2, help_text="Precio minorista en USD", max_digits=10)),
                ("precio_oferta_usd", models.DecimalField(blank=True, decimal_places=2, help_text="Precio promocional en USD", max_digits=10, null=True)),
                ("notas", models.TextField(blank=True, help_text="Notas internas adicionales")),
                ("foto", models.ImageField(blank=True, help_text="Fotografía principal del equipo", null=True, upload_to="iphones/")),
                ("creado", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "variante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_iphone",
                        to="inventario.productovariante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de iPhone",
                "verbose_name_plural": "Detalles de iPhone",
                "ordering": ["-actualizado"],
            },
        ),
    ]
