# Generated by Django 5.2 on 2025-03-07
import django.db.models.deletion
from django.db import migrations, models
from django.db.utils import OperationalError, ProgrammingError


def ensure_variante_column(apps, schema_editor):
    table = "inventario_detalleiphone"
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        tables = connection.introspection.table_names(cursor)
    if table not in tables:
        return

    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, table)
    column_names = {col.name for col in description}
    if "variante_id" in column_names:
        return

    # Add the column allowing NULL values so legacy rows remain valid.
    with connection.cursor() as cursor:
        cursor.execute("ALTER TABLE inventario_detalleiphone ADD COLUMN variante_id bigint NULL")

    vendor = connection.vendor
    if vendor == "mysql":
        with connection.cursor() as cursor:
            try:
                cursor.execute(
                    "ALTER TABLE inventario_detalleiphone "
                    "ADD CONSTRAINT inventario_detalleiphone_variante_id_fk "
                    "FOREIGN KEY (variante_id) REFERENCES inventario_productovariante(id) "
                    "ON DELETE CASCADE"
                )
            except (OperationalError, ProgrammingError):
                pass
            try:
                cursor.execute(
                    "CREATE UNIQUE INDEX inventario_detalleiphone_variante_id_uniq "
                    "ON inventario_detalleiphone (variante_id)"
                )
            except (OperationalError, ProgrammingError):
                pass
    elif vendor == "postgresql":
        with connection.cursor() as cursor:
            try:
                cursor.execute(
                    "ALTER TABLE inventario_detalleiphone "
                    "ADD CONSTRAINT inventario_detalleiphone_variante_id_fk "
                    "FOREIGN KEY (variante_id) REFERENCES inventario_productovariante(id) "
                    "ON DELETE CASCADE"
                )
            except (OperationalError, ProgrammingError):
                pass
            try:
                cursor.execute(
                    "CREATE UNIQUE INDEX IF NOT EXISTS inventario_detalleiphone_variante_id_uniq "
                    "ON inventario_detalleiphone (variante_id)"
                )
            except (OperationalError, ProgrammingError):
                pass
    # For SQLite and other backends we skip constraints; the ORM layer remains functional.


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0008_detalleiphone_rebuild"),
    ]

    operations = [
        migrations.RunPython(ensure_variante_column, noop),
        migrations.AlterField(
            model_name="detalleiphone",
            name="variante",
            field=models.OneToOneField(
                blank=True,
                help_text="Variante asociada al equipo dentro del inventario",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalle_iphone",
                to="inventario.productovariante",
            ),
        ),
    ]
