# Generated by Django 5.2.8 on 2025-11-12 18:33

from django.db import migrations, models


def check_column_exists(connection, table_name, column_name):
    """Check if a column exists in a table."""
    vendor = connection.vendor
    with connection.cursor() as cursor:
        if vendor == 'sqlite':
            # SQLite approach
            cursor.execute(
                "PRAGMA table_info(%s)" % table_name
            )
            columns = [row[1] for row in cursor.fetchall()]
            return column_name in columns
        else:
            # MySQL/MariaDB approach
            cursor.execute(
                """
                SELECT COUNT(*) FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s 
                AND COLUMN_NAME = %s
                """,
                [table_name, column_name]
            )
            return cursor.fetchone()[0] > 0


def add_codigo_barras_if_missing(apps, schema_editor):
    """Add codigo_barras column only if it doesn't exist."""
    connection = schema_editor.connection
    table_name = "inventario_productovariante"
    vendor = connection.vendor
    
    if not check_column_exists(connection, table_name, "codigo_barras"):
        with connection.cursor() as cursor:
            if vendor == 'sqlite':
                cursor.execute(
                    f"ALTER TABLE {table_name} ADD COLUMN codigo_barras VARCHAR(64) NULL"
                )
            else:
                cursor.execute(
                    f"ALTER TABLE {table_name} ADD COLUMN codigo_barras VARCHAR(64) NULL"
                )


def add_qr_code_if_missing(apps, schema_editor):
    """Add qr_code column only if it doesn't exist."""
    connection = schema_editor.connection
    table_name = "inventario_productovariante"
    vendor = connection.vendor
    
    if not check_column_exists(connection, table_name, "qr_code"):
        with connection.cursor() as cursor:
            if vendor == 'sqlite':
                cursor.execute(
                    f"ALTER TABLE {table_name} ADD COLUMN qr_code VARCHAR(255) NULL"
                )
            else:
                cursor.execute(
                    f"ALTER TABLE {table_name} ADD COLUMN qr_code VARCHAR(255) NULL"
                )


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_rename_ultima_actualizacion_and_fix_sku'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_codigo_barras_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='productovariante',
                    name='codigo_barras',
                    field=models.CharField(blank=True, help_text='Código de barras EAN/UPC', max_length=64, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_qr_code_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='productovariante',
                    name='qr_code',
                    field=models.CharField(blank=True, help_text='Código QR (URL o texto)', max_length=255, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre'], name='idx_categoria_nombre'),
        ),
        migrations.AddIndex(
            model_name='precio',
            index=models.Index(fields=['activo'], name='idx_precio_activo'),
        ),
        migrations.AddIndex(
            model_name='precio',
            index=models.Index(fields=['variante', 'tipo', 'moneda'], name='idx_precio_var_tipo_mon'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='idx_producto_activo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='idx_producto_nombre'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barras'], name='idx_producto_cod_barras'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['sku'], name='idx_var_sku'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['activo'], name='idx_var_activo'),
        ),
        migrations.AddIndex(
            model_name='productovariante',
            index=models.Index(fields=['stock_actual'], name='idx_var_stock'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['activo'], name='idx_proveedor_activo'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nombre'], name='idx_proveedor_nombre'),
        ),
    ]
