# Generated by Django 5.2.8 on 2025-11-12 20:29

from django.db import migrations, models


def check_column_exists(connection, table_name, column_name):
    """Check if a column exists in a table."""
    vendor = connection.vendor
    with connection.cursor() as cursor:
        if vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(%s)" % table_name)
            columns = [row[1] for row in cursor.fetchall()]
            return column_name in columns
        else:
            cursor.execute(
                """
                SELECT COUNT(*) FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s 
                AND COLUMN_NAME = %s
                """,
                [table_name, column_name]
            )
            return cursor.fetchone()[0] > 0


def ensure_estado_column_has_default(apps, schema_editor):
    """Asegura que la columna estado tenga valores por defecto si están vacíos."""
    connection = schema_editor.connection
    table_name = "inventario_producto"
    
    # Solo actualizar si la columna existe
    if check_column_exists(connection, table_name, "estado"):
        with connection.cursor() as cursor:
            # Actualizar registros existentes que tengan estado NULL o vacío
            cursor.execute(
                "UPDATE inventario_producto SET estado = 'ACTIVO' WHERE estado IS NULL OR estado = ''"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_productovariante_codigo_barras_and_more'),
    ]

    operations = [
        # Solo actualizar el estado de Django, no tocar la base de datos
        # porque la columna 'estado' ya existe
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='producto',
                    name='estado',
                    field=models.CharField(blank=True, default='ACTIVO', help_text='Estado del producto en la base de datos', max_length=20),
                ),
            ],
            database_operations=[
                # Asegurar que los registros existentes tengan un valor por defecto
                migrations.RunPython(ensure_estado_column_has_default, migrations.RunPython.noop),
            ],
        ),
    ]
