# Generated by Django 5.2.8 on 2025-11-12 20:29

from django.db import migrations, models


def ensure_estado_column_has_default(apps, schema_editor):
    """Asegura que la columna estado tenga valores por defecto si están vacíos."""
    from django.db import connection
    with connection.cursor() as cursor:
        # Actualizar registros existentes que tengan estado NULL o vacío
        cursor.execute(
            "UPDATE inventario_producto SET estado = 'ACTIVO' WHERE estado IS NULL OR estado = ''"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_productovariante_codigo_barras_and_more'),
    ]

    operations = [
        # Solo actualizar el estado de Django, no tocar la base de datos
        # porque la columna 'estado' ya existe
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='producto',
                    name='estado',
                    field=models.CharField(blank=True, default='ACTIVO', help_text='Estado del producto en la base de datos', max_length=20),
                ),
            ],
            database_operations=[
                # Asegurar que los registros existentes tengan un valor por defecto
                migrations.RunPython(ensure_estado_column_has_default, migrations.RunPython.noop),
            ],
        ),
    ]
