# Generated by Django 5.2.8 on 2025-11-12 20:38

from django.db import migrations, models


def ensure_nombre_variante_has_default(apps, schema_editor):
    """Asegura que la columna nombre_variante tenga valores por defecto si están vacíos."""
    from django.db import connection
    with connection.cursor() as cursor:
        # Actualizar registros existentes que tengan nombre_variante NULL o vacío
        cursor.execute(
            "UPDATE inventario_productovariante SET nombre_variante = '' WHERE nombre_variante IS NULL"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_add_estado_field_to_producto'),
    ]

    operations = [
        # Solo actualizar el estado de Django, no tocar la base de datos
        # porque la columna 'nombre_variante' ya existe
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='productovariante',
                    name='nombre_variante',
                    field=models.CharField(blank=True, default='', help_text='Nombre descriptivo de la variante', max_length=200),
                ),
            ],
            database_operations=[
                # Asegurar que los registros existentes tengan un valor por defecto
                migrations.RunPython(ensure_nombre_variante_has_default, migrations.RunPython.noop),
            ],
        ),
    ]
