# Generated by Django 5.2.8 on 2025-11-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_add_nombre_variante_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='garantia_dias',
            field=models.PositiveIntegerField(blank=True, help_text='Días de garantía específicos para esta categoría. Si está vacío, se usa la garantía general.', null=True),
        ),
    ]
