# Generated by Django 5.2.8 on 2025-11-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_productoimagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['parent__nombre', 'nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Seleccioná la categoría padre si esta es una subcategoría', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='inventario.categoria', verbose_name='Categoría padre'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['parent'], name='idx_categoria_parent'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('nombre', 'parent'), name='unique_categoria_nombre_parent'),
        ),
    ]
