# Generated by Django 5.2.8 on 2025-11-14 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_conversacion_enhancements'),
        ('inventario', '0017_add_categoria_parent'),
        ('ventas', '0009_venta_descuento_metodo_pago_ars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCanjeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_iphone', models.CharField(help_text='Modelo del iPhone (ej: iPhone 11, iPhone 13 Pro Max)', max_length=100)),
                ('capacidad', models.CharField(help_text='Capacidad de almacenamiento (ej: 128GB, 256GB, 512GB, 1TB)', max_length=20)),
                ('valor_base_canje_usd', models.DecimalField(decimal_places=2, help_text='Valor base del canje en USD para este modelo y capacidad', max_digits=10)),
                ('descuentos_bateria', models.JSONField(blank=True, default=dict, help_text='Descuentos por salud de batería. Ej: {"<80": 0.15, "80-90": 0.10, ">90": 0.0}')),
                ('descuentos_estado', models.JSONField(blank=True, default=dict, help_text='Descuentos por estado físico. Ej: {"excelente": 0.0, "bueno": 0.05, "regular": 0.15}')),
                ('descuentos_accesorios', models.JSONField(blank=True, default=dict, help_text='Descuentos por accesorios faltantes. Ej: {"sin_caja": 0.02, "sin_cargador": 0.01}')),
                ('guia_estado_excelente', models.TextField(blank=True, help_text="Guía: ¿Cuándo considerar 'Excelente'? (ej: Sin rayas, sin golpes visibles, pantalla perfecta)")),
                ('guia_estado_bueno', models.TextField(blank=True, help_text="Guía: ¿Cuándo considerar 'Bueno'? (ej: 1-2 rayitas menores, pequeños arañazos en marco)")),
                ('guia_estado_regular', models.TextField(blank=True, help_text="Guía: ¿Cuándo considerar 'Regular'? (ej: Múltiples rayas, golpes visibles, pantalla con daños menores)")),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, no aparecerá en las opciones de canje')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Plan Canje',
                'verbose_name_plural': 'Configuraciones Plan Canje',
                'ordering': ['modelo_iphone', 'capacidad'],
                'indexes': [models.Index(fields=['modelo_iphone', 'capacidad'], name='idx_plan_canje_modelo_cap'), models.Index(fields=['activo'], name='idx_plan_canje_activo')],
                'unique_together': {('modelo_iphone', 'capacidad')},
            },
        ),
        migrations.CreateModel(
            name='PlanCanjeTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('cliente_documento', models.CharField(blank=True, max_length=40)),
                ('iphone_recibido_modelo', models.CharField(max_length=100)),
                ('iphone_recibido_capacidad', models.CharField(max_length=20)),
                ('iphone_recibido_color', models.CharField(blank=True, max_length=50)),
                ('iphone_recibido_imei', models.CharField(blank=True, max_length=15)),
                ('iphone_recibido_bateria', models.PositiveIntegerField(help_text='Salud de batería (1-100)')),
                ('iphone_recibido_estado', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular')], max_length=20)),
                ('iphone_recibido_accesorios', models.JSONField(blank=True, default=dict, help_text="Accesorios incluidos. Ej: {'caja': True, 'cargador': True, 'cable': False}")),
                ('iphone_recibido_observaciones', models.TextField(blank=True)),
                ('valor_base_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_bateria_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_estado_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_accesorios_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_calculado_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_calculado_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ajuste_manual_ars', models.DecimalField(decimal_places=2, default=0, help_text='Ajuste manual aplicado por el admin (puede ser positivo o negativo)', max_digits=12)),
                ('valor_iphone_entregado_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia_ars', models.DecimalField(decimal_places=2, help_text='Diferencia que debe pagar el cliente (precio nuevo - valor usado + ajuste)', max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canjes_realizados', to='crm.cliente')),
                ('detalle_iphone_recibido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_canje', to='inventario.detalleiphone')),
                ('iphone_entregado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canjes_entregados', to='inventario.productovariante')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canjes_registrados', to=settings.AUTH_USER_MODEL)),
                ('venta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canje_asociado', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Transacción Plan Canje',
                'verbose_name_plural': 'Transacciones Plan Canje',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='idx_canje_fecha'), models.Index(fields=['cliente'], name='idx_canje_cliente')],
            },
        ),
    ]
