# Generated by Django 5.2.8 on 2025-11-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_plan_canje_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancanjeconfig',
            name='descuentos_botones',
            field=models.JSONField(blank=True, default=dict, help_text='Descuentos por estado de botones. Ej: {"todos_funcionan": 0.0, "alguno_no_funciona": 0.05, "varios_no_funcionan": 0.10}'),
        ),
        migrations.AddField(
            model_name='plancanjeconfig',
            name='descuentos_camara',
            field=models.JSONField(blank=True, default=dict, help_text='Descuentos por estado de cámara. Ej: {"perfecta": 0.0, "rayas_menores": 0.02, "rayas_visibles": 0.05, "rota": 0.15}'),
        ),
        migrations.AddField(
            model_name='plancanjeconfig',
            name='descuentos_marco',
            field=models.JSONField(blank=True, default=dict, help_text='Descuentos por estado del marco. Ej: {"perfecto": 0.0, "arañazos": 0.02, "golpes": 0.05, "deformado": 0.10}'),
        ),
        migrations.AddField(
            model_name='plancanjeconfig',
            name='descuentos_pantalla',
            field=models.JSONField(blank=True, default=dict, help_text='Descuentos por estado de pantalla. Ej: {"perfecta": 0.0, "rayas_menores": 0.03, "rayas_visibles": 0.08, "grieta": 0.15}'),
        ),
        migrations.AddField(
            model_name='plancanjetransaccion',
            name='descuento_botones_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='plancanjetransaccion',
            name='descuento_camara_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='plancanjetransaccion',
            name='descuento_marco_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='plancanjetransaccion',
            name='descuento_pantalla_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='plancanjetransaccion',
            name='iphone_recibido_estado_botones',
            field=models.CharField(blank=True, help_text='Estado de botones (todos_funcionan, alguno_no_funciona, varios_no_funcionan)', max_length=50),
        ),
        migrations.AddField(
            model_name='plancanjetransaccion',
            name='iphone_recibido_estado_camara',
            field=models.CharField(blank=True, help_text='Estado de cámara (perfecta, rayas_menores, rayas_visibles, rota)', max_length=50),
        ),
        migrations.AddField(
            model_name='plancanjetransaccion',
            name='iphone_recibido_estado_marco',
            field=models.CharField(blank=True, help_text='Estado del marco (perfecto, arañazos, golpes, deformado)', max_length=50),
        ),
        migrations.AddField(
            model_name='plancanjetransaccion',
            name='iphone_recibido_estado_pantalla',
            field=models.CharField(blank=True, help_text='Estado de la pantalla (perfecta, rayas_menores, rayas_visibles, grieta)', max_length=50),
        ),
        migrations.AlterField(
            model_name='plancanjeconfig',
            name='descuentos_accesorios',
            field=models.JSONField(blank=True, default=dict, help_text='Descuentos por accesorios faltantes. Ej: {"sin_caja": 0.02}'),
        ),
        migrations.AlterField(
            model_name='plancanjeconfig',
            name='guia_estado_bueno',
            field=models.TextField(blank=True, help_text="Guía: ¿Cuándo considerar 'Bueno'? (ej: 1-2 rayitas menores, pequeños arañazos en marco, pantalla con rayas menores)"),
        ),
        migrations.AlterField(
            model_name='plancanjeconfig',
            name='guia_estado_excelente',
            field=models.TextField(blank=True, help_text="Guía: ¿Cuándo considerar 'Excelente'? (ej: Sin rayas, sin golpes visibles, pantalla perfecta, todos los botones funcionan)"),
        ),
        migrations.AlterField(
            model_name='plancanjeconfig',
            name='guia_estado_regular',
            field=models.TextField(blank=True, help_text="Guía: ¿Cuándo considerar 'Regular'? (ej: Múltiples rayas, golpes visibles, pantalla con daños menores, algún botón no funciona)"),
        ),
        migrations.AlterField(
            model_name='plancanjetransaccion',
            name='iphone_recibido_accesorios',
            field=models.JSONField(blank=True, default=dict, help_text="Accesorios incluidos. Ej: {'caja': True}"),
        ),
    ]
