# Generated by Django 5.2.8 on 2025-11-19 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('nombre_comercio', models.CharField(max_length=200, verbose_name='Nombre del Comercio')),
                ('rubro', models.CharField(max_length=100, verbose_name='Rubro')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas de Revisión')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Solicitud Mayorista',
                'verbose_name_plural': 'Solicitudes Mayoristas',
                'ordering': ['-creado'],
            },
        ),
    ]
