# Generated by Django 5.2.8 on 2025-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agregar_solicitud_mayorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='documento',
            field=models.CharField(blank=True, help_text='DNI o documento de identidad', max_length=20, null=True, verbose_name='Documento'),
        ),
    ]
