# Generated by Django 5.2.8 on 2025-11-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfilusuario_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmayorista',
            name='cuit_cuil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT/CUIL'),
        ),
    ]
