# Generated by Django 5.2.8 on 2025-11-21 15:55

from django.db import migrations


def agregar_default_actualizado_todas_tablas(apps, schema_editor):
    """Agrega valor por defecto al campo actualizado en todas las tablas que lo necesiten"""
    from django.db import connection
    
    # Lista de todas las tablas que tienen el campo actualizado
    tablas = [
        'asistente_ia_assistantknowledgearticle',
        'asistente_ia_assistantplaybook',
        'asistente_ia_assistantquickreply',
        'asistente_ia_conversationthread',
        'configuracion_configuraciontienda',
        'configuracion_preferenciausuario',
        'core_direccionenvio',
        'core_perfilusuario',
        'core_solicitudmayorista',
        'crm_clientecontexto',
        'crm_cotizacion',
        'inventario_detalleiphone',
        'inventario_plancanjeconfig',
        'inventario_plancanjetransaccion',
        'inventario_precio',
        'inventario_productoimagen',
        'inventario_productovariante',
        'locales_local',
        'ventas_venta',
    ]
    
    def check_column_default(connection, table_name, column_name):
        """Verifica si una columna tiene un default"""
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT COLUMN_DEFAULT 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s 
                AND COLUMN_NAME = %s
            """, [table_name, column_name])
            result = cursor.fetchone()
            return result and result[0] is not None
    
    with connection.cursor() as cursor:
        for tabla in tablas:
            # Verificar si la tabla existe y si el campo no tiene default
            try:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.COLUMNS 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s 
                    AND COLUMN_NAME = 'actualizado'
                """, [tabla])
                existe = cursor.fetchone()[0] > 0
                
                if existe and not check_column_default(connection, tabla, 'actualizado'):
                    try:
                        cursor.execute(f"""
                            ALTER TABLE {tabla} 
                            MODIFY COLUMN actualizado datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
                        """)
                        print(f"✅ Agregado default a {tabla}.actualizado")
                    except Exception as e:
                        print(f"⚠️  Error en {tabla}: {e}")
            except Exception as e:
                print(f"⚠️  Error verificando {tabla}: {e}")


def reverse_func(apps, schema_editor):
    """Función reversa - no hace nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agregar_cuit_cuil_solicitud'),
    ]

    operations = [
        migrations.RunPython(agregar_default_actualizado_todas_tablas, reverse_func),
    ]
