# Generated by Django 5.2.8 on 2025-11-21 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agregar_default_actualizado_todas_tablas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA_WEB', 'Nueva Venta Web'), ('SOLICITUD_MAYORISTA', 'Nueva Solicitud Mayorista'), ('ERROR_PAGO', 'Error de Pago'), ('STOCK_BAJO', 'Stock Bajo'), ('STOCK_REPOSICION', 'Stock Repuesto'), ('PEDIDO_PENDIENTE', 'Pedido Pendiente de Pago'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('url_relacionada', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Relacionada')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales')),
                ('leida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL, verbose_name='Leída por')),
            ],
            options={
                'verbose_name': 'Notificación Interna',
                'verbose_name_plural': 'Notificaciones Internas',
                'ordering': ['-creada'],
            },
        ),
        migrations.AddIndex(
            model_name='notificacioninterna',
            index=models.Index(fields=['leida', '-creada'], name='core_notifi_leida_9a8f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacioninterna',
            index=models.Index(fields=['tipo', '-creada'], name='core_notifi_tipo_8b3f4e_idx'),
        ),
    ]
