# Generated by Django 5.2.5 on 2025-08-31 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre y Apellido del cliente', max_length=150)),
                ('telefono', models.CharField(help_text='Número de WhatsApp. Debe ser único.', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email del cliente (opcional)', max_length=254, null=True)),
                ('tipo_cliente', models.CharField(choices=[('Minorista', 'Minorista'), ('Mayorista', 'Mayorista'), ('Potencial', 'Potencial'), ('No Potencial', 'No Potencial')], default='Potencial', help_text='Clasificación del cliente', max_length=20)),
                ('instagram_handle', models.CharField(blank=True, help_text='Usuario de Instagram (opcional)', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Instagram', 'Instagram')], max_length=20)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Pendiente', 'Pendiente')], default='Abierta', max_length=20)),
                ('resumen', models.TextField(blank=True, help_text='Resumen de la conversación generado por la IA.')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('asesor_asignado', models.ForeignKey(blank=True, help_text='Asesor humano asignado. Si es Nulo, está siendo manejado por la IA.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='crm.cliente')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(choices=[('Cliente', 'Cliente'), ('Sistema', 'Sistema')], max_length=10)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_por_ia', models.BooleanField(default=False, help_text='Marca si este mensaje fue enviado automáticamente por la IA.')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='crm.conversacion')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
    ]
