# Generated by Django 4.2 on 2025-09-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Sistema', 'Sistema'), ('IA_Nota', 'Nota de IA')], max_length=10),
        ),
    ]
