# Generated by Django 4.2 on 2025-09-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_mensaje_emisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_chat/'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='tipo_mensaje',
            field=models.CharField(default='texto', max_length=20),
        ),
    ]
