# Generated by Django 5.2.8 on 2025-11-14 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_conversacion_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteContexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos_interes', models.JSONField(default=list, help_text='Lista de productos que el cliente ha consultado o mostrado interés')),
                ('categorias_preferidas', models.JSONField(default=list, help_text='Categorías de productos que más consulta')),
                ('tipo_consulta_comun', models.CharField(blank=True, help_text='Tipo de consulta más común (compra, stock, precio, etc.)', max_length=50)),
                ('ultima_interaccion', models.DateTimeField(auto_now=True)),
                ('total_interacciones', models.IntegerField(default=0)),
                ('promedio_respuesta_segundos', models.FloatField(blank=True, help_text='Tiempo promedio que tarda en responder (si aplica)', null=True)),
                ('notas_internas', models.TextField(blank=True, help_text='Notas internas sobre el cliente (no se muestran al cliente)')),
                ('tags_comportamiento', models.JSONField(default=list, help_text="Tags automáticos sobre el comportamiento (ej: 'comprador frecuente', 'consulta precios')")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contexto', to='crm.cliente')),
            ],
            options={
                'verbose_name': 'Contexto del Cliente',
                'verbose_name_plural': 'Contextos de Clientes',
            },
        ),
    ]
