# Generated by Django 5.2.8 on 2025-11-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_clientecontexto'),
        ('ventas', '0009_venta_descuento_metodo_pago_ars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.JSONField(help_text="Lista de productos con precios: [{'sku': '...', 'nombre': '...', 'cantidad': 1, 'precio': 1000}]")),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valido_hasta', models.DateTimeField(help_text='Fecha de expiración de la cotización')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviada', 'Enviada'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Expirada', 'Expirada')], default='Pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre la cotización')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='crm.cliente')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='crm.conversacion')),
                ('venta_relacionada', models.ForeignKey(blank=True, help_text='Venta creada a partir de esta cotización', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-creado'],
            },
        ),
    ]
