# Generated by Django 5.2.8 on 2025-11-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, help_text='DNI o documento de identidad (opcional)', max_length=40, null=True),
        ),
    ]
