# Generated by Django 5.2.8 on 2025-11-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_venta_descuento_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_unitario_usd_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio original en USD si fue convertido', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='tipo_cambio_usado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tipo de cambio usado para la conversión', max_digits=10, null=True),
        ),
    ]
