# Generated by Django 5.2.8 on 2025-11-12 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_add_nombre_variante_field'),
        ('ventas', '0004_detalleventa_precio_unitario_usd_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='variante',
            field=models.ForeignKey(blank=True, help_text='Null para productos varios', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.productovariante'),
        ),
    ]
