# Generated by Django 5.2.8 on 2025-11-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_make_variante_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_pago_mixto',
            field=models.BooleanField(default=False, help_text='Indica si la venta tiene múltiples métodos de pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago_2',
            field=models.CharField(blank=True, choices=[('EFECTIVO_ARS', 'Efectivo ARS'), ('EFECTIVO_USD', 'Efectivo USD'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], help_text='Segundo método de pago si es pago mixto', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pago_1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del primer método de pago', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_pago_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del segundo método de pago (restante)', max_digits=12, null=True),
        ),
    ]
