# Generated by Django 5.2.8 on 2025-11-13 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_categoria_garantia_dias'),
        ('ventas', '0006_venta_es_pago_mixto_venta_metodo_pago_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='variante',
            field=models.ForeignKey(blank=True, help_text='Null para productos varios o productos eliminados', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_venta', to='inventario.productovariante'),
        ),
        migrations.CreateModel(
            name='CarritoRemoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, help_text='Lista de items en el carrito remoto')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_remoto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito Remoto',
                'verbose_name_plural': 'Carritos Remotos',
            },
        ),
    ]
