# Generated by Django 5.2.8 on 2025-11-13 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_detalleventa_variante_carritoremoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('error', models.TextField(blank=True, help_text='Mensaje de error si falla la impresión')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_impresion', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_impresion', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Solicitud de Impresión',
                'verbose_name_plural': 'Solicitudes de Impresión',
                'ordering': ['-creado'],
            },
        ),
    ]
