# Generated by Django 5.2.8 on 2025-11-13 14:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_solicitudimpresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_metodo_pago_ars',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Descuentos aplicados por método de pago', max_digits=12),
        ),
    ]
