# Generated by Django 5.2.8 on 2025-11-19 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_venta_descuento_metodo_pago_ars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Motivo de cancelación o devolución si aplica', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='origen',
            field=models.CharField(choices=[('POS', 'POS'), ('WEB', 'Web')], default='POS', help_text='Origen de la venta: POS o Web', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='status',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('PENDIENTE_ARMADO', 'Pendiente de armado'), ('LISTO_RETIRAR', 'Listo para retirar'), ('EN_CAMINO', 'En camino / Enviado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto'), ('PENDIENTE_ENVIO', 'Pendiente de envío')], default='PENDIENTE_PAGO', max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialEstadoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('PENDIENTE_ARMADO', 'Pendiente de armado'), ('LISTO_RETIRAR', 'Listo para retirar'), ('EN_CAMINO', 'En camino / Enviado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto'), ('PENDIENTE_ENVIO', 'Pendiente de envío')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('PENDIENTE_ARMADO', 'Pendiente de armado'), ('LISTO_RETIRAR', 'Listo para retirar'), ('EN_CAMINO', 'En camino / Enviado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto'), ('PENDIENTE_ENVIO', 'Pendiente de envío')], max_length=20, verbose_name='Estado Nuevo')),
                ('nota', models.TextField(blank=True, help_text='Nota adicional sobre el cambio de estado', null=True, verbose_name='Nota')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_venta', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Venta',
                'verbose_name_plural': 'Historiales de Estado de Venta',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['venta', '-creado'], name='ventas_hist_venta_i_65b196_idx')],
            },
        ),
    ]
