# Generated by Django 5.2.8 on 2025-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_agregar_estados_pago_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercadopago_link', 'MercadoPago Link'), ('tarjeta', 'Tarjeta'), ('EFECTIVO_ARS', 'Efectivo ARS'), ('EFECTIVO_USD', 'Efectivo USD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercadopago_link', 'MercadoPago Link'), ('tarjeta', 'Tarjeta'), ('EFECTIVO_ARS', 'Efectivo ARS'), ('EFECTIVO_USD', 'Efectivo USD')], help_text='Segundo método de pago si es pago mixto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='origen',
            field=models.CharField(choices=[('web', 'Web'), ('local', 'Local'), ('mayorista', 'Mayorista'), ('POS', 'POS')], default='local', help_text='Origen de la venta: web, local o mayorista', max_length=20),
        ),
    ]
