# Generated by Django 5.2.8 on 2025-11-21 15:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_add_plan_canje_new_fields'),
        ('ventas', '0012_alter_venta_metodo_pago_alter_venta_metodo_pago_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Cupón')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto Fijo')], default='PORCENTAJE', max_length=20, verbose_name='Tipo de Descuento')),
                ('valor_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje (0-100) o monto fijo según el tipo', max_digits=10, verbose_name='Valor del Descuento')),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto mínimo de compra para aplicar el cupón', max_digits=12, verbose_name='Monto Mínimo')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('usos_maximos', models.IntegerField(default=0, help_text='0 = ilimitado', verbose_name='Usos Máximos')),
                ('usos_actuales', models.IntegerField(default=0, verbose_name='Usos Actuales')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('solo_mayoristas', models.BooleanField(default=False, help_text='Si está marcado, solo usuarios mayoristas pueden usar este cupón', verbose_name='Solo Mayoristas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-creado'],
            },
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Venta'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        # Remover campos solo si existen (usar RunPython para verificar)
        migrations.RunPython(
            lambda apps, schema_editor: None,  # No hacer nada en forward
            lambda apps, schema_editor: None,   # No hacer nada en reverse
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_cupon_ars',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Descuento por Cupón'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.productovariante'),
        ),
        migrations.AlterField(
            model_name='historialestadoventa',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historialestadoventa',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('PENDIENTE_ARMADO', 'Pendiente de armado'), ('LISTO_RETIRAR', 'Listo para retirar'), ('EN_CAMINO', 'En camino / Enviado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto'), ('PENDIENTE_ENVIO', 'Pendiente de envío')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialestadoventa',
            name='estado_nuevo',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('PENDIENTE_ARMADO', 'Pendiente de armado'), ('LISTO_RETIRAR', 'Listo para retirar'), ('EN_CAMINO', 'En camino / Enviado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto'), ('PENDIENTE_ENVIO', 'Pendiente de envío')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historialestadoventa',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialestadoventa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialestadoventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='ventas.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento_metodo_pago_ars',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='es_pago_mixto',
            field=models.BooleanField(default=False, verbose_name='Es Pago Mixto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('retirado', 'Retirado')], default='pendiente', max_length=20, verbose_name='Estado de Entrega'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('error', 'Error'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercadopago_link', 'MercadoPago Link'), ('tarjeta', 'Tarjeta'), ('EFECTIVO_ARS', 'Efectivo ARS'), ('EFECTIVO_USD', 'Efectivo USD')], max_length=20, null=True, verbose_name='Método de Pago 2'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_pago_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Pagado con Método 1'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_pago_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Pagado con Método 2'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación/Devolución'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='origen',
            field=models.CharField(choices=[('web', 'Web'), ('local', 'Local'), ('mayorista', 'Mayorista'), ('POS', 'POS')], default='POS', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='status',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('PENDIENTE_ARMADO', 'Pendiente de armado'), ('LISTO_RETIRAR', 'Listo para retirar'), ('EN_CAMINO', 'En camino / Enviado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto'), ('PENDIENTE_ENVIO', 'Pendiente de envío')], default='PENDIENTE_PAGO', max_length=30),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cupon', verbose_name='Cupón Aplicado'),
        ),
    ]
