# Generated by Django 5.2.8 on 2025-11-21 15:44

from django.db import migrations, models
import django.utils.timezone


def agregar_default_actualizado(apps, schema_editor):
    """Agrega valor por defecto al campo actualizado si no existe"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Verificar si el campo ya tiene un default
        cursor.execute("""
            SELECT COLUMN_DEFAULT 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'ventas_cupon' 
            AND COLUMN_NAME = 'actualizado'
        """)
        result = cursor.fetchone()
        
        # Si no tiene default, agregarlo
        if result and result[0] is None:
            cursor.execute("""
                ALTER TABLE ventas_cupon 
                MODIFY COLUMN actualizado datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
            """)


def reverse_func(apps, schema_editor):
    """Función reversa - no hace nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_agregar_cupones'),
    ]

    operations = [
        migrations.RunPython(agregar_default_actualizado, reverse_func),
    ]
