# Generated by Django 5.2.8 on 2025-11-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_agregar_default_actualizado_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio_unitario_usd_original',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='tipo_cambio_usado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='comprobante_pdf',
        ),
        migrations.AddField(
            model_name='venta',
            name='comprobante_url',
            field=models.URLField(blank=True, help_text='URL del PDF del comprobante almacenado en Bunny Storage', max_length=500, null=True, verbose_name='URL del Comprobante PDF'),
        ),
    ]
