# Generated by Django 5.2.8 on 2025-11-21 22:58

from django.db import migrations, models


def check_table_exists(connection, table_name):
    """Verifica si una tabla existe"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.TABLES 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = %s
        """, [table_name])
        return cursor.fetchone()[0] > 0


def check_column_exists(connection, table_name, column_name):
    """Verifica si una columna existe en una tabla"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = %s 
            AND COLUMN_NAME = %s
        """, [table_name, column_name])
        return cursor.fetchone()[0] > 0


def remove_field_if_exists(apps, schema_editor):
    """Remueve campos solo si existen"""
    db_alias = schema_editor.connection.alias
    connection = schema_editor.connection
    
    # Verificar y remover campos de detalleventa
    if check_table_exists(connection, 'ventas_detalleventa'):
        if check_column_exists(connection, 'ventas_detalleventa', 'precio_unitario_usd_original'):
            with connection.cursor() as cursor:
                cursor.execute("ALTER TABLE ventas_detalleventa DROP COLUMN precio_unitario_usd_original")
        
        if check_column_exists(connection, 'ventas_detalleventa', 'tipo_cambio_usado'):
            with connection.cursor() as cursor:
                cursor.execute("ALTER TABLE ventas_detalleventa DROP COLUMN tipo_cambio_usado")
    
    # Verificar y remover campos de venta
    if check_table_exists(connection, 'ventas_venta'):
        if check_column_exists(connection, 'ventas_venta', 'actualizado'):
            with connection.cursor() as cursor:
                cursor.execute("ALTER TABLE ventas_venta DROP COLUMN actualizado")
        
        if check_column_exists(connection, 'ventas_venta', 'comprobante_pdf'):
            with connection.cursor() as cursor:
                cursor.execute("ALTER TABLE ventas_venta DROP COLUMN comprobante_pdf")


def add_comprobante_url_if_table_exists(apps, schema_editor):
    """Agrega el campo comprobante_url solo si la tabla existe"""
    db_alias = schema_editor.connection.alias
    connection = schema_editor.connection
    
    # Verificar si la tabla existe antes de agregar el campo
    if check_table_exists(connection, 'ventas_venta'):
        if not check_column_exists(connection, 'ventas_venta', 'comprobante_url'):
            with connection.cursor() as cursor:
                cursor.execute("""
                    ALTER TABLE ventas_venta 
                    ADD COLUMN comprobante_url VARCHAR(500) NULL
                """)


def reverse_add_comprobante_url(apps, schema_editor):
    """Reversa la operación"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_agregar_default_actualizado_carrito'),
    ]

    operations = [
        migrations.RunPython(
            remove_field_if_exists,
            reverse_remove_field,
        ),
        migrations.RunPython(
            add_comprobante_url_if_table_exists,
            reverse_add_comprobante_url,
        ),
        # Actualizar el estado de Django (siempre se ejecuta para mantener consistencia)
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Ya se hizo con RunPython
            state_operations=[
                migrations.AddField(
                    model_name='venta',
                    name='comprobante_url',
                    field=models.URLField(blank=True, help_text='URL del PDF del comprobante almacenado en Bunny Storage', max_length=500, null=True, verbose_name='URL del Comprobante PDF'),
                ),
            ],
        ),
    ]
