# Generated by Django 5.2.8 on 2025-11-12 17:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locales', '0001_initial'),
        ('ventas', '0003_remove_venta_descuento_general_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('monto_inicial_ars', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_cierre_real_ars', models.DecimalField(blank=True, decimal_places=2, help_text='Conteo físico de efectivo', max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='locales.local')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_aperturadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja Diaria',
                'verbose_name_plural': 'Cajas Diarias',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APERTURA', 'Apertura'), ('VENTA', 'Venta'), ('RETIRO', 'Retiro'), ('INGRESO_EXTRA', 'Ingreso Extra')], max_length=20)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO_ARS', 'Efectivo ARS'), ('EFECTIVO_USD', 'Efectivo USD'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], max_length=20)),
                ('monto_ars', models.DecimalField(decimal_places=2, help_text='Negativo para retiros', max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('caja_diaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja.cajadiaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL)),
                ('venta_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='cajadiaria',
            index=models.Index(fields=['local', 'estado'], name='idx_caja_local_estado'),
        ),
        migrations.AddIndex(
            model_name='cajadiaria',
            index=models.Index(fields=['fecha_apertura'], name='idx_caja_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['caja_diaria', 'tipo'], name='idx_mov_caja_tipo'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['venta_asociada'], name='idx_mov_venta'),
        ),
    ]
