# Generated by Django 5.2.8 on 2025-11-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuraciontienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontienda',
            name='garantia_dias_general',
            field=models.PositiveIntegerField(default=45, help_text='Días de garantía por defecto para todos los productos'),
        ),
    ]
