# Generated by Django 5.2.8 on 2025-11-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_configuraciontienda_garantia_dias_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='correo_contacto',
            field=models.EmailField(blank=True, help_text='Correo de contacto principal.', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='costo_envio_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de envío local.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='costo_envio_nacional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de envío nacional base.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='descuento_efectivo_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Porcentaje de descuento por pago en efectivo o transferencia.', max_digits=5),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='envios_disponibles',
            field=models.BooleanField(default=True, help_text='Realiza envíos.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='envios_locales',
            field=models.CharField(blank=True, help_text='Ej: moto, cadetería, mensajería', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='envios_nacionales',
            field=models.CharField(blank=True, help_text='Ej: correo, expreso', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='facebook',
            field=models.URLField(blank=True, help_text='URL de la página de Facebook.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='URL completa de Google Maps al local.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='horario_domingos',
            field=models.CharField(blank=True, help_text='Ej: Cerrado o 10:00 - 14:00', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='horario_lunes_a_viernes',
            field=models.CharField(blank=True, help_text='Ej: 9:00 - 18:00', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='horario_sabados',
            field=models.CharField(blank=True, help_text='Ej: 9:00 - 13:00', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='instagram_empresa',
            field=models.CharField(blank=True, help_text='Usuario de Instagram de la empresa (sin @).', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='instagram_principal',
            field=models.CharField(blank=True, help_text='Usuario de Instagram principal (sin @).', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='instagram_secundario',
            field=models.CharField(blank=True, help_text='Usuario de Instagram secundario (sin @).', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='nombre_local',
            field=models.CharField(blank=True, help_text='Nombre del local físico (puede diferir del nombre comercial).', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='pago_efectivo_local',
            field=models.BooleanField(default=True, help_text='Acepta pago en efectivo en el local.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='pago_efectivo_retiro',
            field=models.BooleanField(default=True, help_text='Acepta pago en efectivo al retirar.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='pago_online',
            field=models.BooleanField(default=False, help_text='Acepta pago online.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='pago_online_link',
            field=models.URLField(blank=True, help_text='Link o QR para pago online.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='pago_tarjeta',
            field=models.BooleanField(default=True, help_text='Acepta tarjetas de crédito y débito.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='pago_transferencia',
            field=models.BooleanField(default=True, help_text='Acepta transferencia bancaria.'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='politica_envio',
            field=models.TextField(blank=True, help_text='Política de envíos (texto breve).'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='telefono_local',
            field=models.CharField(blank=True, help_text='Teléfono fijo del local.', max_length=40),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='telefono_whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp alternativo (si difiere del principal).', max_length=40),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='tiktok',
            field=models.CharField(blank=True, help_text='Usuario de TikTok (sin @).', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='transferencia_alias',
            field=models.CharField(blank=True, help_text='Alias de transferencia bancaria.', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='transferencia_cbu',
            field=models.CharField(blank=True, help_text='CBU para transferencias.', max_length=22),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='ubicacion_mapa',
            field=models.CharField(blank=True, help_text='Descripción breve de la ubicación para mostrar en mapas.', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='whatsapp_alternativo',
            field=models.CharField(blank=True, help_text='Número de WhatsApp alternativo para mostrar.', max_length=40),
        ),
    ]
