# Generated by Django 5.2.8 on 2025-11-21 15:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def check_column_exists(connection, table_name, column_name):
    """Verifica si una columna existe en una tabla"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = %s 
            AND COLUMN_NAME = %s
        """, [table_name, column_name])
        return cursor.fetchone()[0] > 0


def check_table_exists(connection, table_name):
    """Verifica si una tabla existe"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.TABLES 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = %s
        """, [table_name])
        return cursor.fetchone()[0] > 0


def add_fields_if_not_exists(apps, schema_editor):
    """Agrega campos solo si no existen"""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Agregar cantidad_minima_mayorista si no existe
        if not check_column_exists(connection, 'configuracion_configuracionsistema', 'cantidad_minima_mayorista'):
            cursor.execute("""
                ALTER TABLE configuracion_configuracionsistema 
                ADD COLUMN cantidad_minima_mayorista INTEGER NOT NULL DEFAULT 0
            """)
        
        # Agregar monto_minimo_mayorista si no existe
        if not check_column_exists(connection, 'configuracion_configuracionsistema', 'monto_minimo_mayorista'):
            cursor.execute("""
                ALTER TABLE configuracion_configuracionsistema 
                ADD COLUMN monto_minimo_mayorista DECIMAL(12, 2) NOT NULL DEFAULT 0.00
            """)
        
        # Agregar precios_escala_activos si no existe
        if not check_column_exists(connection, 'configuracion_configuracionsistema', 'precios_escala_activos'):
            cursor.execute("""
                ALTER TABLE configuracion_configuracionsistema 
                ADD COLUMN precios_escala_activos BOOLEAN NOT NULL DEFAULT 0
            """)
        
        # Agregar horarios_apertura si no existe
        if not check_column_exists(connection, 'configuracion_configuracionsistema', 'horarios_apertura'):
            cursor.execute("""
                ALTER TABLE configuracion_configuracionsistema 
                ADD COLUMN horarios_apertura VARCHAR(100) NULL
            """)
        
        # Agregar instagram_personal si no existe
        if not check_column_exists(connection, 'configuracion_configuracionsistema', 'instagram_personal'):
            cursor.execute("""
                ALTER TABLE configuracion_configuracionsistema 
                ADD COLUMN instagram_personal VARCHAR(100) NULL
            """)
        
        # Crear tabla EscalaPrecioMayorista si no existe
        if not check_table_exists(connection, 'configuracion_escalapreciomayorista'):
            cursor.execute("""
                CREATE TABLE configuracion_escalapreciomayorista (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    cantidad_minima INTEGER NOT NULL,
                    cantidad_maxima INTEGER NULL,
                    porcentaje_descuento DECIMAL(5, 2) NOT NULL,
                    activo BOOLEAN NOT NULL DEFAULT 1,
                    orden INTEGER NOT NULL DEFAULT 0,
                    configuracion_id BIGINT NULL,
                    FOREIGN KEY (configuracion_id) REFERENCES configuracion_configuracionsistema(id) ON DELETE CASCADE,
                    INDEX idx_escala_config (configuracion_id)
                )
            """)


def reverse_func(apps, schema_editor):
    """Función reversa - no hace nada"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_agregar_campos_crm_ia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'verbose_name': 'Configuración del Sistema', 'verbose_name_plural': 'Configuración del Sistema'},
        ),
        migrations.RunPython(add_fields_if_not_exists, reverse_func),
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Ya se ejecutó en RunPython
            state_operations=[
                migrations.AddField(
                    model_name='configuracionsistema',
                    name='cantidad_minima_mayorista',
                    field=models.IntegerField(default=0, help_text='Cantidad mínima de unidades para usuarios mayoristas', verbose_name='Cantidad Mínima Mayorista'),
                ),
                migrations.AddField(
                    model_name='configuracionsistema',
                    name='horarios_apertura',
                    field=models.CharField(blank=True, help_text="Horarios de atención (ej: 'Lun-Vie 9-18hs').", max_length=100),
                ),
                migrations.AddField(
                    model_name='configuracionsistema',
                    name='instagram_personal',
                    field=models.CharField(blank=True, help_text='Usuario de Instagram personal (sin @).', max_length=100),
                ),
                migrations.AddField(
                    model_name='configuracionsistema',
                    name='monto_minimo_mayorista',
                    field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto mínimo de compra para usuarios mayoristas', max_digits=12, verbose_name='Monto Mínimo Mayorista'),
                ),
                migrations.AddField(
                    model_name='configuracionsistema',
                    name='precios_escala_activos',
                    field=models.BooleanField(default=False, help_text='Si está activado, se aplicarán descuentos por cantidad a los precios mayoristas', verbose_name='Activar Precios por Escala'),
                ),
                migrations.CreateModel(
                    name='EscalaPrecioMayorista',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('cantidad_minima', models.IntegerField(help_text='Cantidad mínima de unidades para este rango', verbose_name='Cantidad Mínima')),
                        ('cantidad_maxima', models.IntegerField(blank=True, help_text='Cantidad máxima de unidades para este rango (null = sin límite)', null=True, verbose_name='Cantidad Máxima')),
                        ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento a aplicar sobre el precio mayorista base (ej: 5.00 = 5%)', max_digits=5, verbose_name='Porcentaje de Descuento')),
                        ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                        ('orden', models.IntegerField(default=0, help_text='Orden de aplicación (menor = primero)', verbose_name='Orden')),
                        ('configuracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas_precio', to='configuracion.configuracionsistema')),
                    ],
                    options={
                        'verbose_name': 'Escala de Precio Mayorista',
                        'verbose_name_plural': 'Escalas de Precio Mayorista',
                        'ordering': ['orden', 'cantidad_minima'],
                    },
                ),
            ]
        ),
    ]
