# Generated by Django 5.2.8 on 2025-11-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_agregar_precios_escala_mayorista'),
        ('inventario', '0019_add_plan_canje_new_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='correo_contacto',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='google_maps_url',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='horario_domingos',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='horario_lunes_a_viernes',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='horario_sabados',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='instagram_principal',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='politica_envio',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='telefono_local',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='telefono_whatsapp',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='ultima_actualizacion',
        ),
        migrations.AddField(
            model_name='escalapreciomayorista',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categorías a las que se aplica este descuento. Si no se selecciona ninguna, se aplica a todas las categorías.', to='inventario.categoria', verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='costo_envio_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de envío local (opcional).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='costo_envio_nacional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de envío nacional (opcional).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='envios_locales',
            field=models.CharField(blank=True, help_text='Zonas de envío local (barrios, ciudades).', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='envios_nacionales',
            field=models.BooleanField(default=False, help_text='Realiza envíos a todo el país.'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ubicacion_mapa',
            field=models.CharField(blank=True, help_text='URL de Google Maps o coordenadas del local.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='escalapreciomayorista',
            index=models.Index(fields=['configuracion', 'activo', 'orden'], name='configuraci_configu_0bb6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='escalapreciomayorista',
            index=models.Index(fields=['cantidad_minima', 'cantidad_maxima'], name='configuraci_cantida_64b3cf_idx'),
        ),
    ]
