# Generated by Django 4.2 on 2025-09-02 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('ELIMINACION', 'Eliminación'), ('ESTADO', 'Cambio de Estado'), ('VENTA', 'Venta')], help_text='El tipo de acción realizada.', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción.')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que ocurrió la acción.')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Historial',
                'verbose_name_plural': 'Registros de Historial',
                'ordering': ['-fecha'],
            },
        ),
    ]
